//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLogistics
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logistic
    {
        public int Logistic_id { get; set; }
        public string Payment_id { get; set; }
        public string User_id { get; set; }
        public string Order_id { get; set; }
        public string Address { get; set; }
        public int Amount { get; set; }
        public int Price { get; set; }
        public string Delivery_status { get; set; }
        public string Delivery_type { get; set; }
        public string Delivery_Date { get; set; }
        public string Expected_date { get; set; }
    }
}
